### ISSUE TITLE
Guidance on more/less output of git log should be provided the first time it's used

### ISSUE THREAD

**Issue by cpswan** [ianmiell/learngitthehardway#4]
Readers are told to `hit q to exit` during the section on detached HEAD, but they've already struggled past the more (or is it less) style output by then (when they do `git log` after cloning the shutit repo). Anybody used to a *nix command line will likely already know how to deal with more, but Windows users with git bash might be out of their depth the first time they run `git log`.

```
$ git log
Hit q to exit the log output.
```

**Comment by ianmiell** [comment]
The previous references to `git log` before shutit are on histories that are very short.

Are there cases where git log pages even if it doesn't fill the screen? Or are you concerned that screens will be small for some users and they will hit this problem earlier?

**Comment by cpswan** [comment]
The very first cases are short, but when people get into the clone section the shutit logs are large enough to use more.

**Comment by ianmiell** [comment]
The first mention of git log in clone already tells the user to hit q to exit:

```
This shows you a default history of the repository. Page through a few times                                                                                                                              
and you will see how far it goes back. Hit `q` to stop viewing it and return                                                                                                                              
to the command line.             
```

Have added a little on what 'page' means.
