### ISSUE TITLE
I'm or I am

### ISSUE THREAD

**Issue by cpswan** [ianmiell/learngitthehardway#6]
In the stash section the commit message is `'Some changes I am not sure about'` because I'm would cause issues with quoting, but the git diff shown below is `+Some changes I'm not sure about...`

Besides getting consistency between parts of the text it might be worth explicitly tackling how to deal with saying `I'm` in a commit message (or didn't or doesn't etc.).

**Comment by ianmiell** [comment]
Corrected. Quoting in shell is a hairy topic I'd rather not broach (I think it's covered in LBTHW).

Closing, thanks.
