### ISSUE TITLE
Inconsistency of directory naming

### ISSUE THREAD

**Issue by cpswan** [ianmiell/learngitthehardway#7]
After naming all of the directories `lgthw_git_whatever` the Git Add Interactive section then starts using a directory called `2.2.1`. There's also inconsistency in whether `git` is in the directory name or not (and since the whole thing is about git it seems superfluous).

**Comment by ianmiell** [comment]
Fixed that and the following directory.
Also removed inconsistent usage of '&&'.

**Comment by ianmiell** [comment]
Closing, thanks.
